### ISSUE TITLE
Freefem 4.8 tag ARPACK linking fails on petsc-slepc

### ISSUE THREAD

**Issue by VesaIhanainen** [FreeFem/FreeFem-sources#172] opened 2021-04-16 09:29 UTC
I am on openSUSE Tumbleweed and it appears that ARPACK is built to `FreeFem-installation-4.8/ff-petsc/r/lib64/ `rather than `FreeFem-installation-4.8/ff-petsc/r/lib/`. After moving ARPACK files to` FreeFem-installation-4.8/ff-petsc/r/lib/` it seems to be fixed and build correctly. However HPDDM seems to after SLEPc is compiled correctly, should I make a separate issue for the HPDDM problem?

Here is (hopefully) all relevant information on the build.

`la ../../../FreeFem-installation-4.8/ff-petsc/r/lib64`

```
-rw-r--r-- 1 ve users  3.0M Apr 16 12:17 libarpack.a
-rwxr-xr-x 1 ve users   994 Apr 16 12:17 libarpack.la
lrwxrwxrwx 1 ve users    18 Apr 16 12:17 libarpack.so -> libarpack.so.2.1.0
lrwxrwxrwx 1 ve users    18 Apr 16 12:17 libarpack.so.2 -> libarpack.so.2.1.0
-rwxr-xr-x 1 ve users  917K Apr 16 12:17 libarpack.so.2.1.0
-rw-r--r-- 1 ve users  3.8M Apr 16 12:17 libparpack.a
-rwxr-xr-x 1 ve users  1.1K Apr 16 12:17 libparpack.la
lrwxrwxrwx 1 ve users    19 Apr 16 12:17 libparpack.so -> libparpack.so.2.1.0
lrwxrwxrwx 1 ve users    19 Apr 16 12:17 libparpack.so.2 -> libparpack.so.2.1.0
-rwxr-xr-x 1 ve users 1017K Apr 16 12:17 libparpack.so.2.1.0
drwxr-xr-x 1 ve users    18 Apr 16 12:17 pkgconfig
```

Building with

`autoreconf -i`

Output:

```
configure.ac:1003: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:1094: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:1003: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:1094: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:1003: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:1094: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:1003: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:1094: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:1003: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:1094: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:1003: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:1094: warning: file `etc/config/m4/acmpi.m4' included several times
configure.ac:198: installing './compile'
configure.ac:297: installing './config.guess'
configure.ac:297: installing './config.sub'
configure.ac:34: installing './install-sh'
configure.ac:34: installing './missing'
parallel-tests: installing './test-driver'
plugin/seq/Makefile.am: installing './depcomp'
```

`./configure --enable-download --enable-optim --prefix=${HOME}/dev/freefem/FreeFem-installation-4.8
`
Output: See [configure-output-202104161228.txt](https://github.com/FreeFem/FreeFem-sources/files/6323967/configure-output-202104161228.txt)

`./3rdparty/getall -a`

Output: everything seems to be fine

`cd 3rdparty/ff-petsc`

`make petsc-slepc
`

```
*** Building SLEPc ***
**************************ERROR*************************************
Error building SLEPc. Check fr/lib/petsc/conf/slepc.log
********************************************************************
gmake[3]: *** [/home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2/fr/lib/petsc/conf/petscrules:29: slepcbuild] Error 1
gmake[2]: *** [makefile:295: install] Error 2
make[1]: *** [GNUmakefile:17: install] Error 2
make[1]: Leaving directory '/home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2'
make: *** [Makefile:209: petsc-3.14.2/tag-install-real] Error 2

```
```
cat ./petsc-3.14.2/fr/lib/petsc/conf/slepc.log
Checking environment... done
Checking PETSc installation... done
Checking LAPACK library... done
Checking SCALAPACK... done
Installing ARPACK version 3.7.0...
ERROR: Unable to link with ARPACK library in directories /home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib with libraries and link flags -Wl,-rpath,/home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib -L/home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib -lparpack -larpack
ERROR: See "installed-arch-linux2-c-opt/lib/slepc/conf/configure.log" file for details
```

**Comment by prj-** [comment] 2021-04-16 09:51
This may be fixed in the `develop` branch, but I can't tell you for sure. One way to bypass the issue is to simply apply the following diff, which removes all occurences of `--download-arpack`:
```
diff --git a/3rdparty/ff-petsc/Makefile b/3rdparty/ff-petsc/Makefile
index 9e22278f..6651667b 100644
--- a/3rdparty/ff-petsc/Makefile
+++ b/3rdparty/ff-petsc/Makefile
@@ -91,3 +91,3 @@ PETSC_DOWNLOAD_C += --with-mpi-dir=$(DIR_INSTALL_REAL)
 ifneq ($(FC),)
-PETSC_DOWNLOAD += --with-fc='$(FC)' --download-scalapack --download-mumps --download-slepc-configure-arguments="--download-arpack=https://github.com/prj-/arpack-ng/archive/b64dccb.tar.gz"
+PETSC_DOWNLOAD += --with-fc='$(FC)' --download-scalapack --download-mumps
 PETSC_DOWNLOAD_C += --with-scalapack-dir=$(DIR_INSTALL_REAL) --with-mumps-dir=$(DIR_INSTALL_REAL) # --download-slepc-configure-arguments="--with-arpack-dir=$(DIR_INSTALL_REAL)"
@@ -100,3 +100,3 @@ ifneq ($(MPIFC),)
 COMMON_FLAGS += --with-fc='$(MPIFC)'
-PETSC_DOWNLOAD += --download-scalapack --download-mumps --download-slepc-configure-arguments="--download-arpack=https://github.com/prj-/arpack-ng/archive/b64dccb.tar.gz"
+PETSC_DOWNLOAD += --download-scalapack --download-mumps
 PETSC_DOWNLOAD_C += --with-scalapack-dir=$(DIR_INSTALL_REAL) --with-mumps-dir=$(DIR_INSTALL_REAL) # --download-slepc-configure-arguments="--with-arpack-dir=$(DIR_INSTALL_REAL)"
@@ -126,3 +126,3 @@ ifneq ($(FC),)
 COMMON_FLAGS += --with-fc='$(FC)'
-PETSC_DOWNLOAD += --download-scalapack --download-mumps --download-slepc-configure-arguments="--download-arpack=https://github.com/prj-/arpack-ng/archive/6d11c37b2dc9110f3f6a434029353ae1c5112227.tar.gz"
+PETSC_DOWNLOAD += --download-scalapack --download-mumps
 PETSC_DOWNLOAD_C += --with-scalapack-dir=$(DIR_INSTALL_REAL) --with-mumps-dir=$(DIR_INSTALL_REAL) # --download-slepc-configure-arguments="--with-arpack-dir=$(DIR_INSTALL_REAL)"
```

**Comment by prj-** [comment] 2021-04-16 09:56
What is the error you get after SLEPc? Let's not open up another issue, I'll help you out here directly.

**Comment by VesaIhanainen** [comment] 2021-04-16 10:12
`make petsc-slepc`

```*** Building SLEPc ***
*** Installing SLEPc ***
*** Building and installing HPDDM ***
**************************ERROR*************************************
Error building HPDDM. Check fr/lib/petsc/conf/hpddm.log
********************************************************************
gmake[3]: *** [/home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2/fr/lib/petsc/conf/petscrules:68: hpddmbuild] Error 1
gmake[2]: *** [makefile:295: install] Error 2
make[1]: *** [GNUmakefile:17: install] Error 2
make[1]: Leaving directory '/home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2'
make: *** [Makefile:209: petsc-3.14.2/tag-install-real] Error 2
```

`cat petsc-3.14.2/fr/lib/petsc/conf/hpddm.log`

```
[omitted warnings]
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libhpddm_petsc.so.sPgPgq.ltrans0.ltrans.o: relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libhpddm_petsc.so.sPgPgq.ltrans1.ltrans.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libhpddm_petsc.so.sPgPgq.ltrans2.ltrans.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libhpddm_petsc.so.sPgPgq.ltrans3.ltrans.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libhpddm_petsc.so.sPgPgq.ltrans4.ltrans.o: relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libhpddm_petsc.so.sPgPgq.ltrans5.ltrans.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libhpddm_petsc.so.sPgPgq.ltrans6.ltrans.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libhpddm_petsc.so.sPgPgq.ltrans4.ltrans.o: warning: relocation against `petsc_wait_all_ct' in read-only section `.text'
```

See for full log [hpdmm.log-202104161304.txt](https://github.com/FreeFem/FreeFem-sources/files/6324174/hpdmm.log-202104161304.txt)

I think it might be related to the MPICH but I am not sure if HPDDM uses MPICH. The `./configure --enable-download --enable-optim --prefix=${HOME}/dev/freefem/FreeFem-installation-4.8` prints some errors related to MPICH:
```
checking for MPIRUN... checking for mpirun... /usr/lib64/mpi/gcc/mpich/bin/mpirun
/usr/lib64/mpi/gcc/mpich/bin/mpirun
checking for MPIRUN option: ... [mpiexec@localhost.localdomain] match_arg (utils/args/args.c:160): unrecognized argument oversubscribe
[mpiexec@localhost.localdomain] HYDU_parse_array (utils/args/args.c:175): argument matching returned error
[mpiexec@localhost.localdomain] parse_args (ui/mpich/utils.c:1603): error parsing input array
[mpiexec@localhost.localdomain] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1655): unable to parse user arguments
[mpiexec@localhost.localdomain] main (ui/mpich/mpiexec.c:128): error parsing parameters

checking for mpipath ...
checking for mpic++... /usr/lib64/mpi/gcc/mpich/bin/mpic++
checking for MPICXX... yes
checking MPI_DOUBLE_COMPLEX... yes
checking for mpif90... /usr/lib64/mpi/gcc/mpich/bin/mpif90
ls: cannot access 'mpicxx/libmpi.*': No such file or directory
ls: invalid option -- '/'
Try 'ls --help' for more information.
ls: unrecognized option '--enable-new-dtags/libmpi.*'
Try 'ls --help' for more information.
ls: cannot access 'mpi/libmpi.*': No such file or directory
ls: cannot access '/usr/lib]/libmpi.*': No such file or directory
checking for mpicc... /usr/lib64/mpi/gcc/mpich/bin/mpicc
configure:     ++ add mpifc : -L/usr/lib64/mpi/gcc/mpich/lib64 -lmpifort -Wl,-rpath -Wl,/usr/lib64/mpi/gcc/mpich/lib64 -Wl,--enable-new-dtags -lmpi  ;  -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -I/usr/lib64/mpi/gcc/mpich/include  in  plugin/seq/WHERE_LIBRARY-config "
configure:     ++ add mpif77 : -L/usr/lib64/mpi/gcc/mpich/lib64 -lmpifort -Wl,-rpath -Wl,/usr/lib64/mpi/gcc/mpich/lib64 -Wl,--enable-new-dtags -lmpi  ;  -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -I/usr/lib64/mpi/gcc/mpich/include  in  plugin/seq/WHERE_LIBRARY-config "
```

The MPICH is installed from the openSUSE repos and I ran the `. /usr/lib64/mpi/gcc/mpich/bin/mpivars.sh` before compiling. `mpiexec --version` gives following output
```
mpiexec --version
HYDRA build details:
    Version:                                 3.4.1
    Release Date:                            Fri Jan 22 14:17:48 CST 2021
    CC:                              gcc  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -fPIC -flto=auto -ffat-lto-objects
    Configure options:                       '--disable-option-checking' '--prefix=/usr/lib64/mpi/gcc/mpich' '--host=x86_64-suse-linux-gnu' '--build=x86_64-suse-linux-gnu' '--program-prefix=' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-dependency-tracking' '--exec-prefix=/usr/lib64/mpi/gcc/mpich' '--datadir=/usr/lib64/mpi/gcc/mpich/share' '--bindir=/usr/lib64/mpi/gcc/mpich/bin' '--includedir=/usr/lib64/mpi/gcc/mpich/include' '--libdir=/usr/lib64/mpi/gcc/mpich/lib64' '--libexecdir=/usr/lib64/mpi/gcc/mpich/lib64' '--mandir=/usr/lib64/mpi/gcc/mpich/share/man' '--docdir=/usr/share/doc/mpich' '--disable-rpath' '--disable-wrapper-rpath' '--with-device=ch4:ucx' 'CFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -fPIC -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -O2' 'CXXLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -fPIC' 'MPICHLIB_CFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g' 'MPICHLIB_CXXFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g' 'build_alias=x86_64-suse-linux-gnu' 'host_alias=x86_64-suse-linux-gnu' 'LDFLAGS=-flto=auto -ffat-lto-objects' 'CXXFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -O2' 'FCFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -O2' 'FFLAGS=-fallow-argument-mismatch -O2' '--cache-file=/dev/null' '--srcdir=.' 'CC=gcc' 'LIBS=-lucp -lucp -ljson-c ' 'CPPFLAGS= -DNETMOD_INLINE=__netmod_inline_ucx__ -I/home/abuild/rpmbuild/BUILD/mpich-3.4.1/src/mpl/include -I/home/abuild/rpmbuild/BUILD/mpich-3.4.1/src/mpl/include -I/home/abuild/rpmbuild/BUILD/mpich-3.4.1/modules/yaksa/src/frontend/include -I/home/abuild/rpmbuild/BUILD/mpich-3.4.1/modules/yaksa/src/frontend/include -I/usr/include/json-c -D_REENTRANT -I/home/abuild/rpmbuild/BUILD/mpich-3.4.1/src/mpi/romio/include' 'MPLLIBNAME=mpl'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Demux engines available:                 poll select
```

`mpivars.sh` seems to add `$PATH`, `$MANPATH` and `$LD_LIBRARY_PATH` for MPICH.

**Comment by prj-** [comment] 2021-04-16 10:17
Could you please upload `petsc-3.14.2/fr/lib/petsc/conf/configure.log`?

**Comment by VesaIhanainen** [comment] 2021-04-16 10:20
Here you go.

[petsc-configure.log](https://github.com/FreeFem/FreeFem-sources/files/6324225/petsc-configure.log)

**Comment by prj-** [comment] 2021-04-16 10:55
Thanks. That's a strange one... Could you please try to edit `petsc-3.14.2/config/BuildSystem/config/packages/hpddm.py`, line 78 or so, `ldflags += ' '+self.libraries.toStringNoDupes(dlib)`, add just below:
```
          ldflags += ' '+self.getSharedFlag(self.getCompilerFlags())
```
You'll need to `make petsc-slepc` again. If this still fails, please send the updated `configure.log`.

**Comment by VesaIhanainen** [comment] 2021-04-16 11:13
`petsc-3.14.2/config/BuildSystem/config/packages/hpddm.py` after the modification:
```
        cxxflags += ' '+self.headers.toStringNoDupes(dinclude)
        ldflags += ' '+self.libraries.toStringNoDupes(dlib)
        ldflags += ' '+self.getSharedFlag(self.getCompilerFlags())
        slepcbuilddep = 'slepc-install slepc-build'
```

I checked the diff but it didn't give any differences to the `petsc-configure.log` I uploaded earlier. So I ran reconfigure in the root source directory and `make petsc-slepc` second time but the diff didn't change. Anyway here is the both before and after reconfigure `petsc-3.14.2/fr/lib/petsc/conf/configure.log` logs

[petsc-configure-hpddm-py-mod.txt](https://github.com/FreeFem/FreeFem-sources/files/6324475/petsc-configure-hpddm-py-mod.txt)
[petsc-configure.log-reconfigure-hpddm-py-mod.txt](https://github.com/FreeFem/FreeFem-sources/files/6324476/petsc-configure.log-reconfigure-hpddm-py-mod.txt)

**Comment by prj-** [comment] 2021-04-16 11:50
It seems you `./reconfigure` FreeFEM but not PETSc. Because both logs have the same configure time at the bottom.
```
================================================================================
Finishing configure run at Fri, 16 Apr 2021 12:12:24 +0300
================================================================================
```
What you need to do, is go in `3rdparty/ff-petsc`, change `petsc-3.14.2/config/BuildSystem/config/packages/hpddm.py` as you have done just above, then `rm -rf petsc-3.14.2/tag-conf*`, and `make petsc-slepc`. You'll need to double check that `petsc-lite-3.14.2.tar.gz` is not being re-unpacked, otherwise that would override your changes to `hpddm.py`. Thank you for your help and patience.

**Comment by VesaIhanainen** [comment] 2021-04-16 12:06
I think this one should be the correct `petsc-configure.log` after the `petsc-3.14.2/config/BuildSystem/config/packages/hpddm.py` modification.

[petsc-configure-petsc-reconf.txt](https://github.com/FreeFem/FreeFem-sources/files/6324741/petsc-configure-petsc-reconf.txt)

**Comment by prj-** [comment] 2021-04-16 12:11
Yes, it seems there is no `-fPIC` flag for the HPDDM rule. Could you try to type the following command in your terminal, please:
```
$ /usr/lib64/mpi/gcc/mpich/bin/mpic++  -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fstack-protector -fvisibility=hidden -O3 -mtune=native    -I/home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/include -I/home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2/include -I/home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2/fr/externalpackages/git.hpddm/include /home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2/fr/externalpackages/git.hpddm/interface/hpddm_petsc.cpp  --shared -Wl,-rpath,/home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib -L/home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib -lslepc  -o /home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib/libhpddm_petsc.so

**Comment by VesaIhanainen** [comment] 2021-04-16 12:13
The 

```
 /usr/lib64/mpi/gcc/mpich/bin/mpic++  -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fstack-protector -fvisibility=hidden -O3 -mtune=native    -I/home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/include -I/home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2/include -I/home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2/fr/externalpackages/git.hpddm/include /home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2/fr/externalpackages/git.hpddm/interface/hpddm_petsc.cpp  --shared -Wl,-rpath,/home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib -L/home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib -lslepc  -o /home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib/libhpddm_petsc.so```

Ran fine and there wasn't any error, should I continue with `make petsc-slepc` or continue with building the FeeFem?

**Comment by prj-** [comment] 2021-04-16 12:25
If you need PETSc in complex arithmetic, I think you have to do the following:
```
$ touch petsc-3.14.2/tag-install-real
$ make petsc-slepc
```
The first line is to trick FreeFEM into thinking that the install went fine (though it didn't and we had to finish by hands) for real arithmetic.
Then, go back to FreeFEM root directory, `./reconfigure && make`.

**Comment by VesaIhanainen** [comment] 2021-04-16 13:03
I compiled the petsc-slepc for complex arithmetic with the instructions above and the same problem came up. I ran the 
```
 /usr/lib64/mpi/gcc/mpich/bin/mpic++  -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fstack-protector -fvisibility=hidden -O3 -mtune=native    -I/home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/include -I/home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2/include -I/home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2/fr/externalpackages/git.hpddm/include /home/ve/dev/freefem/FreeFem-sources-4.8/3rdparty/ff-petsc/petsc-3.14.2/fr/externalpackages/git.hpddm/interface/hpddm_petsc.cpp  --shared -Wl,-rpath,/home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib -L/home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib -lslepc  -o /home/ve/dev/freefem/FreeFem-installation-4.8/ff-petsc/r/lib/libhpddm_petsc.so
```
again with changing all `FreeFem-installation-4.8/ff-petsc/r/` to `FreeFem-installation-4.8/ff-petsc/c/`, added the `touch petsc-3.14.2/tag-install-complex` tag and ran the `./reconfigure && make`. This results in an error with `cannot find -lipopt` and `cannot find -lnlopt_cxx`. Here is the build log from `make > build-log.log`
[build-log.log](https://github.com/FreeFem/FreeFem-sources/files/6325207/build-log.log)

**Comment by prj-** [comment] 2021-04-16 13:26
The same error for PETSc complex is to be expected, I'll try to fix this issue for an upcoming release (you don't have a Docker image for your build by any chance?). For Ipopt and NLOpt, I don't use these software and usually configure FreeFEM with `--disable-ipopt --disable-nlopt` to avoid compilation failures.

**Comment by VesaIhanainen** [comment] 2021-04-16 14:07
Thanks for the help! :+1:  After disabling the `ipopt` and `nlopt` the build succeeded and there weren't any errors in the `make check`. I don't have a docker build but I might be able to make one for openSUSE when I have more time.

**Comment by prj-** [comment] 2021-04-16 14:18
It's OK, I've got one, I'll try to fix the ARPACK and HPDDM issues, thank you for bringing this to my attention.

**Comment by prj-** [comment] 2021-04-18 11:10
These issues are fixed using a development copy of PETSc (precisely the `release` branch). If you want, I can create a specific branch with the appropriate PETSc tarball.

**Comment by VesaIhanainen** [comment] 2021-04-18 11:21
Well I got it installed on both machines so I won't be needing `PETSc` tarball.  Once again thanks for the help!

**Comment by prj-** [comment] 2021-04-18 11:23
OK, hopefully, next time you update, it will be a smoother ride! I'll close the issue for now but if you run into additional troubles don't hesitate to re-open it. Thanks.

**Closed by prj-** 2021-04-18 11:23 UTC
