### ISSUE TITLE
Can FreeFem be used in Windows 10?

### ISSUE THREAD

**Issue by SamaHans** [FreeFem/FreeFem-sources#206] opened 2021-11-06 15:29 UTC
If yes, how to configure the environment？

**Comment by prj-** [comment] 2021-11-06 15:38
Either download the `.exe` that we automatically create for each release (https://github.com/FreeFem/FreeFem-sources/releases) or re-compile it yourself (https://doc.freefem.org/introduction/installation.html#compilation-on-windows). Let me know if you need further assistance.

**Comment by SamaHans** [comment] 2021-11-09 04:28
When I try to compile FreeFEM on Windows, there's a problem as:
Makefile:24: Makefile.inc: No such file or directory
make: *** No rule to make target '../../config.status', needed by 'Makefile.inc'.  Stop.
Does anyone know how to deal with it? Thanks!

**Comment by SamaHans** [comment] 2021-11-09 04:42
There's error executing ./configure.
configure: error:  Sorry missing  unzip,m4,bison,flex,patch command !

**Comment by prj-** [comment] 2021-11-09 05:14
I don’t think you followed the instructions close enough as these dependencies are installed with the pacman command.

**Comment by SamaHans** [comment] 2021-11-09 07:32
<img width="429" alt="捕获" src="https://user-images.githubusercontent.com/12651419/140881203-3faa14c1-8ea9-4cbd-80e4-f581098ab081.PNG">

**Comment by SamaHans** [comment] 2021-11-09 08:10
It says that command "autoreconf" cannot be found...

**Comment by prj-** [comment] 2021-11-09 08:45
There are multiple commands from the instructions to get all dependencies up and running. You are only showing the first one, did you run the others?

**Comment by SamaHans** [comment] 2021-11-09 12:33
Yep. I have done all the commands following the instructions. But the command "autoreconf" cannot be found.

**Comment by prj-** [comment] 2021-11-09 12:41
Where do you need `autoreconf`? It's supposed to be `autoconf`.

**Comment by prj-** [comment] 2021-11-09 12:41
`pacman -S base-devel`

**Comment by SamaHans** [comment] 2021-11-09 14:51
Sorry but that does not work.

**Comment by frederichecht** [comment] 2021-11-09 15:10
Dear user ,please read de doc:

Close the MSYS2 shell once you’re asked to. There are now 3 MSYS subsystems installed: MSYS2, MinGW32 and MinGW64. They can respectively be launched from C:devmsys64msys2.exe, C:devmsys64mingw32.exe and C:devmsys64mingw64.exe Reopen MSYS2 (doesn’t matter which version, since we’re merely installing packages). Repeatedly run the following command until it says there are no further updates. You might have to restart your shell again.

1 pacman -Syuu
Now that MSYS2 is fully up-to-date, install the following dependancies

for 64 bit systems:

1 pacman -S autoconf make automake-wrapper bison git \
2   mingw-w64-x86_64-freeglut mingw-w64-x86_64-toolchain \
3   mingw-w64-x86_64-openblas patch python perl pkg-config pkgfile \
4   rebase tar time tzcode unzip which mingw-w64-x86_64-libmicroutils \
5   --ignore mingw-w64-x86_64-gcc-ada --ignore mingw-w64-x86_64-gcc-objc \
6   --ignore mingw-w64-x86_64-gdb mingw-w64-x86_64-cmake --noconfirm
for 32 bit systems (FreeFEM lower than version 4):

1 pacman -S autoconf automake-wrapper bash bash-completion \
2   bison bsdcpio bsdtar bzip2 coreutils curl dash file filesystem \
3   findutils flex gawk gcc gcc-fortran gcc-libs grep gzip inetutils \
4   info less lndir make man-db git mingw-w64-i686-freeglut \
5   mingw-w64-i686-toolchain mingw-w64-i686-gsl mingw-w64-i686-hdf5 \
6   mingw-w64-i686-openblas mintty msys2-keyring msys2-launcher-git \
7   msys2-runtime ncurses pacman pacman-mirrors pactoys-git patch pax-git \
8   perl pkg-config pkgfile rebase sed tar tftp-hpa time tzcode unzip \
9   util-linux which
Open a MingW64 terminal (or MingW32 for old 32 bit FreeFEM version) and compile the FreeFEM source

1 git clone https://github.com/FreeFem/FreeFem-sources
2 cd FreeFem-sources
3 autoreconf -i
4 ./configure --enable-generic --enable-optim \
5   --enable-download --enable-maintainer-mode \
6   CXXFLAGS=-mtune=generic CFLAGS=-mtune=generic \
7   FFLAGS=-mtune=generic --enable-download --disable-hips
8           --prefix=/where/you/want/to/have/files/installed
If you want use HPDDM <https://github.com/hpddm/hpddm> (High Performance Domain Decomposition Methods) for massively parallel computing, install PETSc/SLEPc

1 cd 3rdparty/ff-petsc
2 make petsc-slepc SUDO=sudo
3 cd -
4 ./reconfigure
Download the 3rd party packages and build your FreeFEM library and executable

1 ./3rdparty/getall -a
2 make
3 make check
4 make install
Note
The FreeFEM executable (and some other like ffmedit, …) are in C:\msys64\mingw64\bin (or C:\msys32\mingw32\bin).

**Comment by SamaHans** [comment] 2021-11-10 12:55
Thanks! However, the command "autoreconf -i" just does not work... as shown above. Does anyone else encounter the problem?

**Comment by sgarnotel** [comment] 2021-11-10 17:10
Can you post the output of the following command in the MSYS2 terminal:
```
pacman -S autoconf
```
This one should install the executable `autoreconf`

**Comment by SamaHans** [comment] 2021-11-10 23:29
I have to say that I have carefully done all the commands following the instructions... but the executable `autoreconf` just cannot be found...  I have search all the files on my computer. Also, the executable `make` cannot be found, and the name is given as `mingw32-make.exe` in the bin directory.

**Comment by SamaHans** [comment] 2021-11-11 00:09
Moreover, when trying to do `cmake`, error will occur as 
`-- Building for: Ninja
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_cpp_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/github/cm-master/CMakeFiles/CMakeOutput.log".
`
I'm afraid that the instructions for configuring environment on Windows 10 is not appropriate, as the mingw64 environment seems to be incomplete.

**Comment by SamaHans** [comment] 2021-11-11 09:31
And does anyone else encounter the problem as below ?
`$ cmake .
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_cpp_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/github/cm-master/CMakeFiles/CMakeOutput.log".
`

**Comment by sgarnotel** [comment] 2021-11-11 09:39
I think this is because you installed all the package using the 32bits system, and the compilation wants the 64bits.
I am not a pro on Windows/msys2 but I think you have to look in this way.

**Comment by SamaHans** [comment] 2021-11-11 14:33
Emmm.. I'm sure that I installed all the package using 64bits system as my computer is. It's so weird.

**Comment by frederichecht** [comment] 2021-11-11 16:46
Remark, 
If ma memory is good we you install msys2 you get the both shell one 32 and one 64 
so be careful

**Comment by SamaHans** [comment] 2021-11-12 00:23
yea.. we will get mingw64 and mingw32. But as shown below, it is clear that I use mingw64
<img width="426" alt="捕获" src="https://user-images.githubusercontent.com/12651419/141387610-837665c9-4b2f-4693-9bb7-ba11548d1099.PNG">
.

**Comment by SamaHans** [comment] 2021-11-12 00:23
<img width="426" alt="捕获" src="https://user-images.githubusercontent.com/12651419/141387695-5d0c8811-11fd-4664-ba45-08cb5f9cf222.PNG">
However, it is clear that I use mingw64.

**Comment by prj-** [comment] 2021-11-12 06:43
Are you changing the value of the environment variable `$PATH`?

**Comment by SamaHans** [comment] 2021-11-12 08:13
Yes, I have changed the environment variable so that the command `cmake` and `make`, etc., can be identified.
<img width="286" alt="捕获" src="https://user-images.githubusercontent.com/12651419/141433266-7430be5e-4f15-4b54-afdc-c89e9445ba9e.PNG">
I'm so confused.

**Comment by prj-** [comment] 2021-11-12 08:20
Oh, well, in that case, that probably explains why `autoreconf` is not visible.

**Comment by SamaHans** [comment] 2021-11-12 08:51
Well, I added path `C:\msys64\usr\bin`, then the error comes a
<img width="523" alt="捕获" src="https://user-images.githubusercontent.com/12651419/141438542-36c3dd42-e9c9-45e2-a907-9211442c47f0.PNG">
s

**Comment by prj-** [comment] 2021-11-12 08:53
OK, we're going forward! The thing is, if you played around with your configuration, we can't really tell you what needs to be done because we don't really know what you actually changed. The simplest advice would be to nuke your MSYS2 install and start over from scratch...

**Comment by SamaHans** [comment] 2021-11-12 09:29
Yes I have tried uninstall MSYS2 and install it again. If I don't add path variable, then `make` and `cmake` won't be identified. I didn't change anything else. It's so tiring..

**Comment by SamaHans** [comment] 2021-11-13 02:14
Furthermore, when `cmake`, error occurs as
<img width="522" alt="捕获" src="https://user-images.githubusercontent.com/12651419/141602079-0101fc44-f8fa-4c47-bd28-83bfe8395ca4.PNG">
`Ninja` is not found.

**Comment by SamaHans** [comment] 2021-11-13 02:15
Has anyone successfully complied the stuff?

**Comment by prj-** [comment] 2021-11-13 07:23
Yes, of course. Your problem is very localized, none of us can reproduce this. One alternative would be to download the `.exe` (https://github.com/FreeFem/FreeFem-sources/releases) to install it directly without having to recompile.

**Comment by SamaHans** [comment] 2021-11-13 09:51
Thanks. But does anyone know how to configure the environment on Windows 10? It's so confused. If we follow the instructions, obviously that the commands can't be identified.

**Comment by prj-** [comment] 2021-11-13 10:09
> If we follow the instructions, obviously that the commands can't be identified.

That’s why I’m saying it’s localized to your machine. Those are the exact commands we use on our machines, on our workers for continuous integration, and it works flawlessly. This error has nothing to do with FreeFEM, it’s really specific to your installation. See, e.g., someone with the same issue, which was fixed by the command we already told you to run: https://github.com/msys2/MINGW-packages/issues/1010.

**Comment by SamaHans** [comment] 2021-11-13 13:43
Thanks a lot! There's some progress. But when it comes to `make petsc-slepc SUDO=sudo`, it gives error that `sudo` cannot be identified..

**Comment by SamaHans** [comment] 2021-11-13 13:50
<img width="436" alt="1636811425(1)" src="https://user-images.githubusercontent.com/12651419/141646321-7311bb2c-5405-400f-8f20-11b721fc676a.png">

**Comment by prj-** [comment] 2021-11-13 14:16
I don't understand how there can be progress since are the exact commands we already told you to run, but anyway, you need to remove first the wrong Python by doing `pacman -R mingw-w64-x86_64-python mingw-w64-x86_64-gdb`.
Also, no need to add `SUDO=sudo` in `make petsc-slepc`.

**Comment by SamaHans** [comment] 2021-11-14 01:10
Thanks for your patient explanation. I have reinstalled the system.. However, `pacman -R mingw-w64-x86_64-python mingw-w64-x86_64-gdb` can't be done because there're others depend on them. 
![Uploading 1636852184(1).png…]()

**Comment by SamaHans** [comment] 2021-11-14 01:11
Thanks for your patient explanation. I have reinstalled the system.. However, `pacman -R mingw-w64-x86_64-python `mingw-w64-x86_64-gdb` can't be done because there're others depend on them.
<img width="443" alt="1636852293(1)" src="https://user-images.githubusercontent.com/12651419/141663766-13221e82-cd81-4ba2-b0ed-30ebaa5f3c54.png">

**Comment by prj-** [comment] 2021-11-14 06:54
You should remove those dependencies as well, but it's weird they are here in the first place since they are not part of FreeFEM prerequisites cited in the instructions...

**Comment by SamaHans** [comment] 2021-11-14 09:44
Thanks... but again when do `make petsc-slepc`, error comes as
`Fortran error! mpi_init() could not be located!`. 
Thanks for your considerable answer.

**Comment by prj-** [comment] 2021-11-14 09:45
You need to add the flag `FCFLAGS=-fallow-invalid-boz` in your FreeFEM `./configure` line (this is not documented, yet, sorry about that, it's due to a recent update in gfortran).

**Comment by SamaHans** [comment] 2021-11-14 14:10
Thank you so much! I'm sorry that I have asked so many questions.. now it seems to come to the final steps. 
![image](https://user-images.githubusercontent.com/12651419/141684748-acc902f6-efcb-4e90-be39-dead05ba0fb9.png)

**Comment by prj-** [comment] 2021-11-14 16:01
An issue with your OpenGL installation I guess?

**Comment by SamaHans** [comment] 2021-11-15 00:03
Probably. But how to fix it?

**Comment by SamaHans** [comment] 2021-11-15 06:09
I have checked that `freeglut` is installed.
![image](https://user-images.githubusercontent.com/12651419/141730722-a27a3459-cfd6-4167-ae0f-f467e1bd775b.png)

**Comment by SamaHans** [comment] 2021-11-16 12:08
Does anyone know how to fix it?

**Comment by prj-** [comment] 2021-11-18 12:09
Why do you have `mingw-w64-i686-freeglut`? You are mixing `x86_64` and `i686`, this is likely the root of all your problems (that we cannot reproduce on our installations) since the beginning.

**Comment by SamaHans** [comment] 2021-11-18 13:42
Well I don't have `mingw-w64-i686-freeglut`.. as the picture shows, only `mingw64-w64-x86_64-freeglut` is installed.

**Comment by prj-** [comment] 2021-11-18 13:56
Oops, my bad.

**Comment by SamaHans** [comment] 2021-11-20 14:16
I tried compiling the project under branch develop, and error then comes as
![image](https://user-images.githubusercontent.com/12651419/142729576-bbbab948-a5a5-40a1-9b3b-2f76f36a22dc.png)

**Comment by prj-** [comment] 2021-11-20 17:19
You did not install PETSc, hence the error.

**Comment by prj-** [comment] 2021-11-20 17:23
[Here](https://github.com/FreeFem/FreeFem-sources/blob/master/etc/jenkins/job_Windows/job5.sh#L6) are the exact commands used in our continuous integration tests. This is how we check that we are not breaking anything. But your system seems special, since it's always failing at some point.

**Comment by SamaHans** [comment] 2021-11-21 14:56
So sad.. But I want to give it a last try. Then error comes strangely as
![image](https://user-images.githubusercontent.com/12651419/142767077-b299cd08-62bb-455e-89be-26b06390fb68.png)
reference to XXX is ambiguous.

**Comment by frederichecht** [comment] 2021-11-21 15:00
Yes I know the patch to compile under window with the last msys2 (in progress).

**Comment by SamaHans** [comment] 2021-11-21 15:17
Thanks. So is it a bug when compiling on Win 10?

**Comment by prj-** [comment] 2021-12-22 15:17
@SamaHans, I've been able to reproduce your error, and I have a fix. Are you still interested in trying to get this to compile?
I can provide an up-to-date walk-through if that is the case.

**Comment by SamaHans** [comment] 2022-01-18 14:10
@prj- Thank you so much! Could you please help me with that?

**Comment by prj-** [comment] 2022-01-18 14:12
Sure, I think it would be best if your restart from scratch. So, please, go ahead a clone the `develop` branch of the repository. Then, just `autoreconf -i && ./configure --enable-download --prefix=path_to_your_home/FreeFem-install --disable-fortran && cd 3rdparty/ff-petsc && make petsc-slepc && cd - && ./reconfigure && make && make install`. This should generate the appropriate binaries. Please let me know if you still face some issue.

**Closed** 2022-04-23 20:04 UTC
