### ISSUE TITLE
Solution behaving differently if printing on screen

### ISSUE THREAD

**Issue by antoniofroio** [FreeFem/FreeFem-sources#125] opened 2020-01-14 11:34 UTC
The attached example solves a transient heat conduction problem in cartesian coordinates with varying timestep, and works correctly; however, if commenting out line 109 (which only prints something to the screen), the solution starts behaving badly, i.e. with the minimum and maximum values rapidly diverging, or showing different results on different computers.
The issue is found on FreeFEM++ v4.4 on Windows; Linux version seems to be unaffected, as well as versions <4.
[ex6_tconv.zip](https://github.com/FreeFem/FreeFem-sources/files/4058824/ex6_tconv.zip)

**Comment by prj-** [comment] 2020-05-02 05:30
You may want to add `solver = sparsesolver` to your problem definition. I cannot reproduce this behavior wih FreeFEM 4.6, so I'll close the issue for now.

**Closed by prj-** 2020-05-02 05:30 UTC
