### ISSUE TITLE
FreeFem doesn't compiling on mac M1 (MacBook Air M1, mac os bigsur 11.4)

### ISSUE THREAD

**Issue by rustamNSU** [FreeFem/FreeFem-sources#185] opened 2021-07-22 03:50 UTC
I tried to compile freefem from source file (MacBook Air M1, mac os bigsur 11.4)

0. Installed the minimal libraries for FreeFEM
1. git clone https://github.com/FreeFem/FreeFem-sources.git
2. autoreconf -i
3. ./configure --enable-download --enable-optim
4. ./3rdparty/getall -a
5. cd 3rdparty/ff-petsc
6. make petsc-slepc // add SUDO=sudo if your installation directory is the default /usr/local
7. cd -
8. ./reconfigure
9. sudo make -j4

and got the following compile error (in ipopt package):

checking how to run the C preprocessor... @CXXCPP@
configure: error: C preprocessor "@CXXCPP@" fails sanity check
See `config.log' for more details.
make[5]: *** [Makefile:42: Ipopt-3.12.4/FAIT] Error 1
make[5]: Leaving directory '/Users/rustam/Programs/FreeFem-sources/3rdparty/ipopt'
make[4]: *** [Makefile:991: compile-dir] Error 2
make[4]: Leaving directory '/Users/rustam/Programs/FreeFem-sources/3rdparty'
make[3]: *** [Makefile:1000: tag-compile-pkg] Error 1
make[3]: Leaving directory '/Users/rustam/Programs/FreeFem-sources/3rdparty'
make[2]: *** [Makefile:593: all-recursive] Error 1
make[2]: Leaving directory '/Users/rustam/Programs/FreeFem-sources/3rdparty'
make[1]: *** [Makefile:798: all-recursive] Error 1
make[1]: Leaving directory '/Users/rustam/Programs/FreeFem-sources'
make: *** [Makefile:748: all] Error 2

also i tried (./configure --enable-download CC=gcc-11 CXX=g++-11 F77=gfortran-11 FC=gfortran-11 -with-mpi -with-hdf5=yes) but got same compile error
[config.log](https://github.com/FreeFem/FreeFem-sources/files/6859862/config.log)

**Comment by prj-** [comment] 2021-07-22 06:25
You can bypass this issue by adding `--disable-ipopt` in your configure line.

**Comment by frederichecht** [comment] 2021-07-22 13:20
Dear you can  send a mail to Atsushi Suzuki ***@***.***>
I try to compile on M1 architecture, 


Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
***@***.*** https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by frederichecht** [comment] 2021-07-22 14:17
Dear Frédéric

I have not yet full success in compilation of all 3rd party packages.
I only verified that the main part of FreeFEM can be compiled with Apple clang/clang++, gfortran from "home brew" and OpenMPI which is own compiled by Apple clang.

The issue in compilation of Ipopt-3.12.4 seems to happen on both M1 and Intel with Big Sur with clang/clang++ compiler.
This is caused by 
@CXXCPP@ 
is set as empty.

make CXXCPP = "clang++ -E"
works well to configure IPOPT.

with best regards
22 Jul.2021
Atsushi

>>>>

Subject: Re: [FreeFem/FreeFem-sources] FreeFem doesn't compiling on mac M1
 (MacBook Air M1, mac os bigsur 11.4) (#185)
Date: Thu, 22 Jul 2021 15:15:12 +0200
In-Reply-To: ***@***.***>
Cc: Atsushi Suzuki ***@***.***>
To: FreeFem/FreeFem-sources ***@***.***>
References: ***@***.***>


Dear you can  send a mail to Atsushi Suzuki ***@***.***>
I try to compile on M1 architecture, 


Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
***@***.*** https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by prj-** [comment] 2021-11-13 21:29
This is fixed in FreeFEM version 4.10, feel free to re-open the issue if this still does not work for you.

**Closed by prj-** 2021-11-13 21:29 UTC
