### ISSUE TITLE
more deprecated URL download in ./3rdparty/getall

### ISSUE THREAD

**Issue by johhell** [FreeFem/FreeFem-sources#303] opened 2024-03-16 16:26 UTC
**version**: `git clone https://github.com/FreeFem/FreeFem-sources.git`   March 16, 2024
running `./3rdparty/getall -a` and received a lot of error messages.
see list of files in `./3rdparty/pkg/`   below
refactoring of `getall` would be welcome.

```
size      datetime     name
        0 Mar 16 17:03 arpack96.tar.gz
  2391918 Mar 16 16:45 bemtool.zip
   117283 Jun 25  2017 blas-3.7.1.tgz
        0 Mar 16 17:03 boost_for_bemtool.tar.gz
   197468 Jan 20  2011 cblas.tgz
  4110137 May 28  2018 fftw-3.3.8.tar.gz
        0 Mar 16 17:03 freeyams.2012.02.05.tgz
        0 Mar 16 17:03 gmm-4.2.tar.gz
   468676 Mar 16 16:45 hpddm.zip
  5231190 Mar 16 16:45 htool.zip
  4518646 Aug 10  2015 Ipopt-3.12.4.tgz
        0 Mar 16 17:03 libpthread-google.tar.gz
        0 Mar 16 17:08 list.txt
  4984968 Mar 16 16:43 metis-5.1.0.tar.gz
   158547 Dec 19  2012 mmg3d4.0.tgz
        0 Mar 16 17:03 mmg.zip
        0 Mar 16 17:03 mshmet.2012.04.25.tgz
        0 Mar 16 17:03 MUMPS_5.0.2.tar.gz
  2315878 Jun  9  2011 nlopt-2.2.4.tar.gz
 11920973 Mar 16 16:45 OpenBLAS.tar.gz
  5567670 Mar 16 16:43 ParMetis-4.0.3.tar.gz
        0 Mar 16 17:03 parmmg.zip
        0 Mar 16 17:03 patch.tar.gz
 16975723 Nov 30 20:34 petsc-3.20.2.tar.gz
  5307441 Nov 26  2019 scalapack-2.1.0.tgz
  6292006 Mar 16 16:45 scotch-v6.1.0.tar.gz
 25733849 Aug 16  2021 SuiteSparse-4.4.4.tar.gz
  3443498 Mar 16 16:45 superlu-5.2.2.zip
   280024 Jun  1  2014 tetgen1.5.1-beta1.tar.gz
```

**Comment by prj-** [comment] 2024-03-16 16:50
Duplicate of https://github.com/FreeFem/FreeFem-sources/issues/300.

**Closed by prj-** 2024-03-16 16:50 UTC

**Comment by prj-** [comment] 2024-03-16 16:51
There is no need to refactor `getall`, everything is downloaded and installed by PETSc and this is up-to-date (unlike `getall` which is unmaintained).
