### ISSUE TITLE
Problems with ffddm in FreeFem++

### ISSUE THREAD

**Issue by zhaog6** [FreeFem/FreeFem-sources#103] opened 2019-07-17 05:03 UTC
Dear all,

I have a problem with ffddm.
I downloaded FreeFEM(v4.2-1) from github (`https://github.com/FreeFem/FreeFem-sources.git`) and installed on Ubuntu 18.04 correctly according to the installation guide. When running the file `diffusion-3d-simple.edp` in `ffddm`, I met the following compiling and running error (**load error: metis, and undefined symbol: METIS_PartMeshNodal in the file metis.so**).
> (But It works well using FreeFem++-4.2-1-b-348-MACOS_10.11.pkg on Mac)

```
   15 : IFMACRO(dimension,3S)
   16 & load "msh3"
   17 & macro meshN()meshS// EOM            // three-dimensional surface problem
macro intN()int2d// EOM
macro intbN()int1d// EOM
macro minimalMesh()square3(1,1,[x,y,z])// EOM
ENDIFMACRO
   18 : 
   19 : IFMACRO(WITHHPDDM)
   20 & load "hpddm"
   21 & ENDIFMACRO
  current line = 2 mpirank 2 / 4
   20 : load "hpddm"
   21 : 
   22 : 
  current line = 2 mpirank 3 / 4
   23 : load "thresholdings"
   24 : 
  current line = 2 mpirank 1 / 4
   25 : include "ffddm_partitioning.idp"load "scotch"
    2 : load "metis"
load error : metis
 	 fail : 
 dlerror : /home/zhaog6/zg/FreeFEM/4.2-1/lib/ff++/4.2-1/lib/mpi/metis.so: undefined symbol: METIS_PartMeshNodal
list  prefix: './' '/home/zhaog6/zg/FreeFEM/4.2-1/lib/ff++/4.2-1/lib/mpi/' list  suffix : '' , '.so' 
  current line = 2 mpirank 0 / 4
Load error : metis
	line number :2, metis
error Load error : metis
	line number :2, metis
 code = 2 mpirank: 0
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[33165,1],0]
  Exit code:    2
--------------------------------------------------------------------------
```

**Comment by frederichecht** [comment] 2019-07-17 12:52
Dear The problem is due  to the plugin metis,  
but I down know why it is not compile.
I will see soon has possible but I am I holiday,

Best Regards, 

Frédéric Hecht.   

-----------------------------------------------------------------------------------------------------------------------------------
Laboratoire  Jacques-Louis Lions,                UPMC Sorbonne Université
BC187,  4 Place  Jussieu,     75252  PARIS cedex 05,               France
Campus Jussieu,       Barre 15-25,           3 etage           Bureau 307 
Projet Alpines ,   Inria de Paris, 2 rue Simone Iff Voie DQ12 75012 Paris
tel:  +33 1 44274411,        mob: +33 6 62198986,     fax: +33 1 44277200
frederic.hecht@sorbonne-universite.fr https://www.ljll.math.upmc.fr/hecht
software:  FreeFem++          web site:       http://www.freefem.org/ff++

**Comment by prj-** [comment] 2019-08-22 17:40
This should be fixed now with the latest revision of the develop branch. About your question [here](https://community.freefem.org/t/a-problem-of-parallel-computation-in-3d/95), you can use ffddm (folder `examples/ffddm`, [documentation](https://doc.freefem.org/documentation/ffddm/documentation.html)) or HPDDM and PETSc (folder `examples/hpddm`, [documentation](http://jolivet.perso.enseeiht.fr/FreeFem-tutorial/)). The largest problem I solved with FreeFEM + PETSc had around 50 billion unknowns. Keep in mind that PETSc may scale up to trillion of unknowns, so there is no real limit.

**Closed by prj-** 2019-08-22 17:40 UTC
Labels: bug

**Comment by zhaog6** [comment] 2019-08-23 14:11
The plugin “ffddm” in the newest version on the develop branch works well on my server now.Thank you for your help!
